[loader]
".md" = "text"

[run]
bun = true

[test]
preload = ["./test/setup.ts"]
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { line = 1.0, function = 1.0, statement = 1.0, branch = 1.0 }
