import type {
  CanonicalChordSuffix,
  ChordAliasKey,
  ChordInformation,
  ChordQuality,
  ChordSuffix,
} from './chord-catalog-types.js';

export const CANONICAL_CHORDS: Record<CanonicalChordSuffix, ChordInformation> = {
  major: { symbol: '', intervals: ['perfectUnison', 'majorThird', 'perfectFifth'] },
  minor: { symbol: 'm', intervals: ['perfectUnison', 'minorThird', 'perfectFifth'] },
  diminished: { symbol: 'dim', intervals: ['perfectUnison', 'minorThird', 'diminishedFifth'] },
  augmented: { symbol: 'aug', intervals: ['perfectUnison', 'majorThird', 'augmentedFifth'] },
  power: { symbol: '5', intervals: ['perfectUnison', 'perfectFifth'] },
  suspendedSecond: { symbol: 'sus2', intervals: ['perfectUnison', 'majorSecond', 'perfectFifth'] },
  suspendedFourth: {
    symbol: 'sus4',
    intervals: ['perfectUnison', 'perfectFourth', 'perfectFifth'],
  },
  majorSixth: {
    symbol: '6',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'majorSixth'],
  },
  minorSixth: {
    symbol: 'm6',
    intervals: ['perfectUnison', 'minorThird', 'perfectFifth', 'majorSixth'],
  },
  dominantSeventh: {
    symbol: '7',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'minorSeventh'],
  },
  majorSeventh: {
    symbol: 'maj7',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'majorSeventh'],
  },
  minorSeventh: {
    symbol: 'm7',
    intervals: ['perfectUnison', 'minorThird', 'perfectFifth', 'minorSeventh'],
  },
  minorMajorSeventh: {
    symbol: 'mMaj7',
    intervals: ['perfectUnison', 'minorThird', 'perfectFifth', 'majorSeventh'],
  },
  diminishedSeventh: {
    symbol: 'dim7',
    intervals: ['perfectUnison', 'minorThird', 'diminishedFifth', 'diminishedSeventh'],
  },
  halfDiminishedSeventh: {
    symbol: 'm7b5',
    intervals: ['perfectUnison', 'minorThird', 'diminishedFifth', 'minorSeventh'],
  },
  augmentedSeventh: {
    symbol: '7#5',
    intervals: ['perfectUnison', 'majorThird', 'augmentedFifth', 'minorSeventh'],
  },
  augmentedMajorSeventh: {
    symbol: 'maj7#5',
    intervals: ['perfectUnison', 'majorThird', 'augmentedFifth', 'majorSeventh'],
  },
  dominantSeventhSuspendedSecond: {
    symbol: '7sus2',
    intervals: ['perfectUnison', 'majorSecond', 'perfectFifth', 'minorSeventh'],
  },
  dominantSeventhSuspendedFourth: {
    symbol: '7sus4',
    intervals: ['perfectUnison', 'perfectFourth', 'perfectFifth', 'minorSeventh'],
  },
  dominantSevenFlatNine: {
    symbol: '7♭9',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'minorSeventh', 'minorNinth'],
  },
  dominantSevenSharpNine: {
    symbol: '7♯9',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'minorSeventh', 'augmentedNinth'],
  },
  dominantSevenFlatFive: {
    symbol: '7♭5',
    intervals: ['perfectUnison', 'majorThird', 'diminishedFifth', 'minorSeventh'],
  },
  dominantSevenSharpFive: {
    symbol: '7♯5',
    intervals: ['perfectUnison', 'majorThird', 'augmentedFifth', 'minorSeventh'],
  },
  dominantSevenSharpEleven: {
    symbol: '7♯11',
    intervals: [
      'perfectUnison',
      'majorThird',
      'perfectFifth',
      'minorSeventh',
      'majorNinth',
      'augmentedEleventh',
    ],
  },
  dominantSevenFlatThirteen: {
    symbol: '7♭13',
    intervals: [
      'perfectUnison',
      'majorThird',
      'perfectFifth',
      'minorSeventh',
      'majorNinth',
      'perfectEleventh',
      'minorThirteenth',
    ],
  },
  dominantNinth: {
    symbol: '9',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'minorSeventh', 'majorNinth'],
  },
  majorNinth: {
    symbol: 'maj9',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'majorSeventh', 'majorNinth'],
  },
  minorNinth: {
    symbol: 'm9',
    intervals: ['perfectUnison', 'minorThird', 'perfectFifth', 'minorSeventh', 'majorNinth'],
  },
  dominantEleventh: {
    symbol: '11',
    intervals: [
      'perfectUnison',
      'majorThird',
      'perfectFifth',
      'minorSeventh',
      'majorNinth',
      'perfectEleventh',
    ],
  },
  majorEleventh: {
    symbol: 'maj11',
    intervals: [
      'perfectUnison',
      'majorThird',
      'perfectFifth',
      'majorSeventh',
      'majorNinth',
      'perfectEleventh',
    ],
  },
  minorEleventh: {
    symbol: 'm11',
    intervals: [
      'perfectUnison',
      'minorThird',
      'perfectFifth',
      'minorSeventh',
      'majorNinth',
      'perfectEleventh',
    ],
  },
  dominantThirteenth: {
    symbol: '13',
    intervals: [
      'perfectUnison',
      'majorThird',
      'perfectFifth',
      'minorSeventh',
      'majorNinth',
      'perfectEleventh',
      'majorThirteenth',
    ],
  },
  majorThirteenth: {
    symbol: 'maj13',
    intervals: [
      'perfectUnison',
      'majorThird',
      'perfectFifth',
      'majorSeventh',
      'majorNinth',
      'perfectEleventh',
      'majorThirteenth',
    ],
  },
  minorThirteenth: {
    symbol: 'm13',
    intervals: [
      'perfectUnison',
      'minorThird',
      'perfectFifth',
      'minorSeventh',
      'majorNinth',
      'perfectEleventh',
      'majorThirteenth',
    ],
  },
  addNine: {
    symbol: 'add9',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'majorNinth'],
  },
  minorAddNine: {
    symbol: 'madd9',
    intervals: ['perfectUnison', 'minorThird', 'perfectFifth', 'majorNinth'],
  },
  sixthAddNine: {
    symbol: '6/9',
    intervals: ['perfectUnison', 'majorThird', 'perfectFifth', 'majorSixth', 'majorNinth'],
  },
};

export const CHORD_ALIASES: Record<ChordAliasKey, CanonicalChordSuffix> = {
  majorTriad: 'major',
  minorTriad: 'minor',
  diminishedTriad: 'diminished',
  augmentedTriad: 'augmented',
  powerChord: 'power',
  sus2: 'suspendedSecond',
  sus4: 'suspendedFourth',
  six: 'majorSixth',
  minorSix: 'minorSixth',
  seven: 'dominantSeventh',
  maj7: 'majorSeventh',
  min7: 'minorSeventh',
  minorMaj7: 'minorMajorSeventh',
  minorSevenFlatFive: 'halfDiminishedSeventh',
  dominantSeventhSuspendedSecond: 'dominantSeventhSuspendedSecond',
  dominantSeventhSuspendedFourth: 'dominantSeventhSuspendedFourth',
  '7sus': 'dominantSeventhSuspendedFourth',
  sevenFlatNine: 'dominantSevenFlatNine',
  '7b9': 'dominantSevenFlatNine',
  sevenSharpNine: 'dominantSevenSharpNine',
  '7#9': 'dominantSevenSharpNine',
  sevenFlatFive: 'dominantSevenFlatFive',
  '7b5': 'dominantSevenFlatFive',
  sevenSharpFive: 'dominantSevenSharpFive',
  '7#5': 'dominantSevenSharpFive',
  sevenSharpEleven: 'dominantSevenSharpEleven',
  '7#11': 'dominantSevenSharpEleven',
  sevenFlatThirteen: 'dominantSevenFlatThirteen',
  '7b13': 'dominantSevenFlatThirteen',
  majorSevenSharpFive: 'augmentedMajorSeventh',
  nine: 'dominantNinth',
  maj9: 'majorNinth',
  min9: 'minorNinth',
  eleven: 'dominantEleventh',
  maj11: 'majorEleventh',
  min11: 'minorEleventh',
  thirteen: 'dominantThirteenth',
  maj13: 'majorThirteenth',
  min13: 'minorThirteenth',
  majorAddNine: 'addNine',
  sixNine: 'sixthAddNine',
};

// oxlint-disable-next-line typescript-eslint/no-unsafe-type-assertion
export const CHORDS: Readonly<Record<ChordSuffix, ChordInformation>> = Object.freeze({
  ...CANONICAL_CHORDS,
  ...Object.fromEntries(
    Object.entries(CHORD_ALIASES).map(([alias, suffix]) => [alias, CANONICAL_CHORDS[suffix]]),
  ),
}) as Readonly<Record<ChordSuffix, ChordInformation>>;

export const CHORD_QUALITY_BY_SUFFIX: Record<CanonicalChordSuffix, ChordQuality> = {
  major: 'major',
  majorSixth: 'major',
  majorSeventh: 'major',
  majorNinth: 'major',
  majorEleventh: 'major',
  majorThirteenth: 'major',
  addNine: 'major',
  sixthAddNine: 'major',
  minor: 'minor',
  minorSixth: 'minor',
  minorSeventh: 'minor',
  minorMajorSeventh: 'minor',
  minorNinth: 'minor',
  minorEleventh: 'minor',
  minorThirteenth: 'minor',
  minorAddNine: 'minor',
  diminished: 'diminished',
  diminishedSeventh: 'diminished',
  halfDiminishedSeventh: 'diminished',
  power: 'power',
  augmented: 'augmented',
  augmentedSeventh: 'augmented',
  augmentedMajorSeventh: 'augmented',
  suspendedSecond: 'suspended',
  suspendedFourth: 'suspended',
  dominantSeventh: 'dominant',
  dominantSeventhSuspendedSecond: 'suspended',
  dominantSeventhSuspendedFourth: 'suspended',
  dominantSevenFlatNine: 'altered',
  dominantSevenSharpNine: 'altered',
  dominantSevenFlatFive: 'altered',
  dominantSevenSharpFive: 'altered',
  dominantSevenSharpEleven: 'altered',
  dominantSevenFlatThirteen: 'altered',
  dominantNinth: 'dominant',
  dominantEleventh: 'dominant',
  dominantThirteenth: 'dominant',
};
